-- MySQL Script generated by MySQL Workbench
-- Mon Jul  6 11:49:58 2026
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
-- -----------------------------------------------------
-- Schema usuarios_db
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema usuarios_db
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `usuarios_db` ;
USE `usuarios_db` ;

-- -----------------------------------------------------
-- Table `usuarios_db`.`tipo_usuarios`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `usuarios_db`.`tipo_usuarios` (
  `id_tipo_usuario` INT NOT NULL AUTO_INCREMENT,
  `nombre_tipo` VARCHAR(50) NOT NULL,
  `descripcion_tipo` VARCHAR(100) NOT NULL,
  `created_at` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `updated_at` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  `created_by` VARCHAR(50) NULL DEFAULT NULL,
  `updated_by` VARCHAR(50) NULL DEFAULT NULL,
  `deleted` TINYINT(1) NULL DEFAULT 0,
  UNIQUE INDEX (`id_tipo_usuario` ASC) VISIBLE,
  PRIMARY KEY (`id_tipo_usuario`),
  UNIQUE INDEX (`nombre_tipo` ASC) VISIBLE);


-- -----------------------------------------------------
-- Table `usuarios_db`.`usuarios`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `usuarios_db`.`usuarios` (
  `id_usuario` INT NOT NULL AUTO_INCREMENT,
  `username` VARCHAR(50) NOT NULL,
  `contraseña` VARCHAR(50) NOT NULL,
  `tipo_usuario_id` INT NOT NULL,
  `created_at` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `updated_at` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  `created_by` VARCHAR(50) NULL DEFAULT NULL,
  `updated_by` VARCHAR(50) NULL DEFAULT NULL,
  `deleted` TINYINT(1) NULL DEFAULT 0,
  UNIQUE INDEX (`id_usuario` ASC) VISIBLE,
  PRIMARY KEY (`id_usuario`),
  UNIQUE INDEX (`username` ASC) VISIBLE,
  UNIQUE INDEX (`contraseña` ASC) VISIBLE,
  INDEX (`tipo_usuario_id` ASC) VISIBLE,
  CONSTRAINT ``
    FOREIGN KEY (`tipo_usuario_id`)
    REFERENCES `usuarios_db`.`tipo_usuarios` (`id_tipo_usuario`));


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
