-- MySQL Script generated by MySQL Workbench
-- Thu Jun  4 10:22:06 2026
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
-- -----------------------------------------------------
-- Schema gestion_torneos
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema gestion_torneos
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `gestion_torneos` ;
USE `gestion_torneos` ;

-- -----------------------------------------------------
-- Table `gestion_torneos`.`tipo_usuarios`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `gestion_torneos`.`tipo_usuarios` (
  `id_tipo_usuario` INT NOT NULL AUTO_INCREMENT,
  `nombre_tipo` VARCHAR(50) NOT NULL,
  `descripcion_tipo` VARCHAR(100) NOT NULL,
  `created_at` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `updated_at` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  `created_by` VARCHAR(50) NULL DEFAULT NULL,
  `updated_by` VARCHAR(50) NULL DEFAULT NULL,
  `deleted` TINYINT(1) NULL DEFAULT 0,
  UNIQUE INDEX (`id_tipo_usuario` ASC) VISIBLE,
  PRIMARY KEY (`id_tipo_usuario`),
  UNIQUE INDEX (`nombre_tipo` ASC) VISIBLE);


-- -----------------------------------------------------
-- Table `gestion_torneos`.`paises`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `gestion_torneos`.`paises` (
  `id_pais` INT NOT NULL AUTO_INCREMENT,
  `nombre_pais` VARCHAR(50) NOT NULL,
  `created_at` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `updated_at` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  `created_by` VARCHAR(50) NULL DEFAULT NULL,
  `updated_by` VARCHAR(50) NULL DEFAULT NULL,
  `deleted` TINYINT(1) NULL DEFAULT 0,
  UNIQUE INDEX (`id_pais` ASC) VISIBLE,
  PRIMARY KEY (`id_pais`),
  UNIQUE INDEX (`nombre_pais` ASC) VISIBLE);


-- -----------------------------------------------------
-- Table `gestion_torneos`.`ciudades`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `gestion_torneos`.`ciudades` (
  `id_ciudad` INT NOT NULL AUTO_INCREMENT,
  `nombre_ciudad` VARCHAR(100) NOT NULL,
  `pais_id` INT NOT NULL,
  `created_at` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `updated_at` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  `created_by` VARCHAR(50) NULL DEFAULT NULL,
  `updated_by` VARCHAR(50) NULL DEFAULT NULL,
  `deleted` TINYINT(1) NULL DEFAULT 0,
  UNIQUE INDEX (`id_ciudad` ASC) VISIBLE,
  PRIMARY KEY (`id_ciudad`),
  INDEX (`pais_id` ASC) VISIBLE,
  CONSTRAINT ``
    FOREIGN KEY (`pais_id`)
    REFERENCES `gestion_torneos`.`paises` (`id_pais`));


-- -----------------------------------------------------
-- Table `gestion_torneos`.`usuarios`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `gestion_torneos`.`usuarios` (
  `id_usuario` INT NOT NULL AUTO_INCREMENT,
  `nombre_completo` VARCHAR(100) NOT NULL,
  `email` VARCHAR(100) NOT NULL,
  `username` VARCHAR(50) NOT NULL,
  `ciudad_id` INT NOT NULL,
  `edad` INT NOT NULL,
  `tipo_usuario_id` INT NOT NULL,
  `created_at` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `updated_at` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  `created_by` VARCHAR(50) NULL DEFAULT NULL,
  `updated_by` VARCHAR(50) NULL DEFAULT NULL,
  `deleted` TINYINT(1) NULL DEFAULT 0,
  UNIQUE INDEX (`id_usuario` ASC) VISIBLE,
  PRIMARY KEY (`id_usuario`),
  UNIQUE INDEX (`email` ASC) VISIBLE,
  UNIQUE INDEX (`username` ASC) VISIBLE,
  INDEX (`tipo_usuario_id` ASC) VISIBLE,
  INDEX (`ciudad_id` ASC) VISIBLE,
  CONSTRAINT ``
    FOREIGN KEY (`tipo_usuario_id`)
    REFERENCES `gestion_torneos`.`tipo_usuarios` (`id_tipo_usuario`),
  CONSTRAINT ``
    FOREIGN KEY (`ciudad_id`)
    REFERENCES `gestion_torneos`.`ciudades` (`id_ciudad`));


-- -----------------------------------------------------
-- Table `gestion_torneos`.`equipos`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `gestion_torneos`.`equipos` (
  `id_equipo` INT NOT NULL AUTO_INCREMENT,
  `nombre_equipo` VARCHAR(100) NOT NULL,
  `fecha_creacion` DATE NOT NULL,
  `capitan_id` INT NOT NULL,
  `created_at` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `updated_at` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  `created_by` VARCHAR(50) NULL DEFAULT NULL,
  `updated_by` VARCHAR(50) NULL DEFAULT NULL,
  `deleted` TINYINT(1) NULL DEFAULT 0,
  UNIQUE INDEX (`id_equipo` ASC) VISIBLE,
  PRIMARY KEY (`id_equipo`),
  INDEX (`capitan_id` ASC) VISIBLE,
  CONSTRAINT ``
    FOREIGN KEY (`capitan_id`)
    REFERENCES `gestion_torneos`.`usuarios` (`id_usuario`));


-- -----------------------------------------------------
-- Table `gestion_torneos`.`equipo_usuarios`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `gestion_torneos`.`equipo_usuarios` (
  `id_equipo_usuario` INT NOT NULL AUTO_INCREMENT,
  `equipo_id` INT NOT NULL,
  `usuario_id` INT NOT NULL,
  `fecha_ingreso` DATE NOT NULL,
  `fecha_salida` DATE NULL DEFAULT NULL,
  `created_at` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `updated_at` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  `created_by` VARCHAR(50) NULL DEFAULT NULL,
  `updated_by` VARCHAR(50) NULL DEFAULT NULL,
  `deleted` TINYINT(1) NULL DEFAULT 0,
  PRIMARY KEY (`id_equipo_usuario`),
  INDEX (`equipo_id` ASC) VISIBLE,
  INDEX (`usuario_id` ASC) VISIBLE,
  CONSTRAINT ``
    FOREIGN KEY (`equipo_id`)
    REFERENCES `gestion_torneos`.`equipos` (`id_equipo`),
  CONSTRAINT ``
    FOREIGN KEY (`usuario_id`)
    REFERENCES `gestion_torneos`.`usuarios` (`id_usuario`));


-- -----------------------------------------------------
-- Table `gestion_torneos`.`torneos`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `gestion_torneos`.`torneos` (
  `id_torneo` INT NOT NULL AUTO_INCREMENT,
  `nombre_torneo` VARCHAR(100) NOT NULL,
  `juego` VARCHAR(50) NOT NULL,
  `premio` VARCHAR(255) NULL DEFAULT NULL,
  `fecha_inicio` DATE NOT NULL,
  `fecha_fin` DATE NOT NULL,
  `organizador_id` INT NOT NULL,
  `ciudad_id` INT NOT NULL,
  `created_at` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `updated_at` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  `created_by` VARCHAR(50) NULL DEFAULT NULL,
  `updated_by` VARCHAR(50) NULL DEFAULT NULL,
  `deleted` TINYINT(1) NULL DEFAULT 0,
  PRIMARY KEY (`id_torneo`),
  INDEX (`organizador_id` ASC) VISIBLE,
  INDEX (`ciudad_id` ASC) VISIBLE,
  CONSTRAINT ``
    FOREIGN KEY (`organizador_id`)
    REFERENCES `gestion_torneos`.`usuarios` (`id_usuario`),
  CONSTRAINT ``
    FOREIGN KEY (`ciudad_id`)
    REFERENCES `gestion_torneos`.`ciudades` (`id_ciudad`));


-- -----------------------------------------------------
-- Table `gestion_torneos`.`torneo_equipos`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `gestion_torneos`.`torneo_equipos` (
  `id_torneo_equipo` INT NOT NULL AUTO_INCREMENT,
  `torneo_id` INT NOT NULL,
  `equipo_id` INT NOT NULL,
  `fecha_inscripcion` DATE NOT NULL,
  `created_at` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `updated_at` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  `created_by` VARCHAR(50) NULL DEFAULT NULL,
  `updated_by` VARCHAR(50) NULL DEFAULT NULL,
  `deleted` TINYINT(1) NULL DEFAULT 0,
  PRIMARY KEY (`id_torneo_equipo`),
  UNIQUE INDEX `unique_torneo_equipo` (`torneo_id` ASC, `equipo_id` ASC) VISIBLE,
  INDEX (`torneo_id` ASC) VISIBLE,
  INDEX (`equipo_id` ASC) VISIBLE,
  CONSTRAINT ``
    FOREIGN KEY (`torneo_id`)
    REFERENCES `gestion_torneos`.`torneos` (`id_torneo`),
  CONSTRAINT ``
    FOREIGN KEY (`equipo_id`)
    REFERENCES `gestion_torneos`.`equipos` (`id_equipo`));


-- -----------------------------------------------------
-- Table `gestion_torneos`.`partidas`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `gestion_torneos`.`partidas` (
  `id_partida` INT NOT NULL AUTO_INCREMENT,
  `torneo_id` INT NOT NULL,
  `equipo_local_id` INT NOT NULL,
  `equipo_visitante_id` INT NOT NULL,
  `fecha_partida` DATETIME NOT NULL,
  `ronda` INT NOT NULL,
  `resultado_local` INT NOT NULL DEFAULT 0,
  `resultado_visitante` INT NOT NULL DEFAULT 0,
  `duracion_minutos` INT NOT NULL,
  `ganador_id` INT NULL DEFAULT NULL,
  `created_at` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `updated_at` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  `created_by` VARCHAR(50) NULL DEFAULT NULL,
  `updated_by` VARCHAR(50) NULL DEFAULT NULL,
  `deleted` TINYINT(1) NULL DEFAULT 0,
  PRIMARY KEY (`id_partida`),
  INDEX (`torneo_id` ASC) VISIBLE,
  INDEX (`equipo_local_id` ASC) VISIBLE,
  INDEX (`equipo_visitante_id` ASC) VISIBLE,
  INDEX (`ganador_id` ASC) VISIBLE,
  CONSTRAINT ``
    FOREIGN KEY (`torneo_id`)
    REFERENCES `gestion_torneos`.`torneos` (`id_torneo`),
  CONSTRAINT ``
    FOREIGN KEY (`equipo_local_id`)
    REFERENCES `gestion_torneos`.`equipos` (`id_equipo`),
  CONSTRAINT ``
    FOREIGN KEY (`equipo_visitante_id`)
    REFERENCES `gestion_torneos`.`equipos` (`id_equipo`),
  CONSTRAINT ``
    FOREIGN KEY (`ganador_id`)
    REFERENCES `gestion_torneos`.`equipos` (`id_equipo`));


-- -----------------------------------------------------
-- Table `gestion_torneos`.`sanciones`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `gestion_torneos`.`sanciones` (
  `id_sancion` INT NOT NULL AUTO_INCREMENT,
  `usuario_id` INT NOT NULL,
  `torneo_id` INT NOT NULL,
  `partida_id` INT NULL DEFAULT NULL,
  `motivo` VARCHAR(255) NOT NULL,
  `fecha_sancion` DATE NOT NULL,
  `dias_suspension` INT NOT NULL,
  `created_at` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `updated_at` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  `created_by` VARCHAR(50) NULL DEFAULT NULL,
  `updated_by` VARCHAR(50) NULL DEFAULT NULL,
  `deleted` TINYINT(1) NULL DEFAULT 0,
  UNIQUE INDEX (`id_sancion` ASC) VISIBLE,
  PRIMARY KEY (`id_sancion`),
  INDEX (`usuario_id` ASC) VISIBLE,
  INDEX (`torneo_id` ASC) VISIBLE,
  INDEX (`partida_id` ASC) VISIBLE,
  CONSTRAINT ``
    FOREIGN KEY (`usuario_id`)
    REFERENCES `gestion_torneos`.`usuarios` (`id_usuario`),
  CONSTRAINT ``
    FOREIGN KEY (`torneo_id`)
    REFERENCES `gestion_torneos`.`torneos` (`id_torneo`),
  CONSTRAINT ``
    FOREIGN KEY (`partida_id`)
    REFERENCES `gestion_torneos`.`partidas` (`id_partida`));


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
