-- MySQL Script generated by MySQL Workbench
-- Wed May 27 14:01:12 2026
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
-- -----------------------------------------------------
-- Schema bibliossad
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema bibliossad
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `bibliossad` DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci ;
-- -----------------------------------------------------
-- Schema bibliosSad
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema bibliosSad
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `bibliosSad` ;
USE `bibliossad` ;

-- -----------------------------------------------------
-- Table `bibliossad`.`nacionalidades`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `bibliossad`.`nacionalidades` (
  `id_nacionalidad` INT NOT NULL AUTO_INCREMENT,
  `nombre_nacionalidad` VARCHAR(50) NOT NULL,
  `created_at` TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP,
  `update_at` TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  `created_by` INT NULL DEFAULT NULL,
  `deleted` TINYINT(1) NULL DEFAULT '0',
  PRIMARY KEY (`id_nacionalidad`),
  UNIQUE INDEX `id_nacionalidad` (`id_nacionalidad` ASC) VISIBLE,
  UNIQUE INDEX `nombre_nacionalidad` (`nombre_nacionalidad` ASC) VISIBLE)
ENGINE = InnoDB
AUTO_INCREMENT = 6
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `bibliossad`.`autores`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `bibliossad`.`autores` (
  `id_autor` INT NOT NULL AUTO_INCREMENT,
  `nombre_autor` VARCHAR(50) NOT NULL,
  `apellido_autor` VARCHAR(50) NOT NULL,
  `fecha_nacimiento` DATETIME NOT NULL,
  `fecha_fallecimiento` DATETIME NOT NULL,
  `nacionalidad_id` INT NULL DEFAULT NULL,
  `created_at` TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP,
  `update_at` TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  `created_by` INT NULL DEFAULT NULL,
  `deleted` TINYINT(1) NULL DEFAULT '0',
  PRIMARY KEY (`id_autor`),
  UNIQUE INDEX `id_autor` (`id_autor` ASC) VISIBLE,
  INDEX `nacionalidad_id` (`nacionalidad_id` ASC) VISIBLE,
  CONSTRAINT `autores_ibfk_1`
    FOREIGN KEY (`nacionalidad_id`)
    REFERENCES `bibliossad`.`nacionalidades` (`id_nacionalidad`))
ENGINE = InnoDB
AUTO_INCREMENT = 6
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `bibliossad`.`estados_libros`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `bibliossad`.`estados_libros` (
  `id_estado_libro` INT NOT NULL AUTO_INCREMENT,
  `nombre_estado_libro` VARCHAR(50) NOT NULL,
  `descripcion_estado_libro` VARCHAR(200) NOT NULL,
  `created_at` TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP,
  `update_at` TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  `created_by` INT NULL DEFAULT NULL,
  `deleted` TINYINT(1) NULL DEFAULT '0',
  PRIMARY KEY (`id_estado_libro`),
  UNIQUE INDEX `id_estado_libro` (`id_estado_libro` ASC) VISIBLE,
  UNIQUE INDEX `nombre_estado_libro` (`nombre_estado_libro` ASC) VISIBLE)
ENGINE = InnoDB
AUTO_INCREMENT = 6
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `bibliossad`.`estados_prestamos`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `bibliossad`.`estados_prestamos` (
  `id_estado_prestamo` INT NOT NULL AUTO_INCREMENT,
  `nombre_estado_prestamo` VARCHAR(50) NOT NULL,
  `descripcion_estado_prestamo` VARCHAR(200) NOT NULL,
  `created_at` TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP,
  `update_at` TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  `created_by` INT NULL DEFAULT NULL,
  `deleted` TINYINT(1) NULL DEFAULT '0',
  PRIMARY KEY (`id_estado_prestamo`),
  UNIQUE INDEX `id_estado_prestamo` (`id_estado_prestamo` ASC) VISIBLE,
  UNIQUE INDEX `nombre_estado_prestamo` (`nombre_estado_prestamo` ASC) VISIBLE)
ENGINE = InnoDB
AUTO_INCREMENT = 6
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `bibliossad`.`generos_libros`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `bibliossad`.`generos_libros` (
  `id_genero_libro` INT NOT NULL AUTO_INCREMENT,
  `nombre_genero_libro` VARCHAR(50) NOT NULL,
  `descripcion_genero_libro` VARCHAR(200) NOT NULL,
  `created_at` TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP,
  `update_at` TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  `created_by` INT NULL DEFAULT NULL,
  `deleted` TINYINT(1) NULL DEFAULT '0',
  PRIMARY KEY (`id_genero_libro`),
  UNIQUE INDEX `id_genero_libro` (`id_genero_libro` ASC) VISIBLE,
  UNIQUE INDEX `nombre_genero_libro` (`nombre_genero_libro` ASC) VISIBLE)
ENGINE = InnoDB
AUTO_INCREMENT = 6
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `bibliossad`.`libros`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `bibliossad`.`libros` (
  `id_libro` INT NOT NULL AUTO_INCREMENT,
  `titulo` VARCHAR(50) NOT NULL,
  `resumen_libro` VARCHAR(200) NOT NULL,
  `created_at` TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP,
  `update_at` TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  `created_by` INT NULL DEFAULT NULL,
  `deleted` TINYINT(1) NULL DEFAULT '0',
  `autor_id` INT NOT NULL,
  `genero_id` INT NOT NULL,
  `estado_libro_id` INT NOT NULL,
  PRIMARY KEY (`id_libro`),
  UNIQUE INDEX `id_libro` (`id_libro` ASC) VISIBLE,
  INDEX `autor_id` (`autor_id` ASC) VISIBLE,
  INDEX `genero_id` (`genero_id` ASC) VISIBLE,
  INDEX `estado_libro_id` (`estado_libro_id` ASC) VISIBLE,
  CONSTRAINT `libros_ibfk_1`
    FOREIGN KEY (`autor_id`)
    REFERENCES `bibliossad`.`autores` (`id_autor`),
  CONSTRAINT `libros_ibfk_2`
    FOREIGN KEY (`genero_id`)
    REFERENCES `bibliossad`.`generos_libros` (`id_genero_libro`),
  CONSTRAINT `libros_ibfk_3`
    FOREIGN KEY (`estado_libro_id`)
    REFERENCES `bibliossad`.`estados_libros` (`id_estado_libro`))
ENGINE = InnoDB
AUTO_INCREMENT = 6
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `bibliossad`.`usuarios`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `bibliossad`.`usuarios` (
  `id_usuario` INT NOT NULL AUTO_INCREMENT,
  `nombre_usuario` VARCHAR(50) NOT NULL,
  `correo_usuario` VARCHAR(150) NOT NULL,
  `telefono_usuario` VARCHAR(10) NOT NULL,
  `created_at` TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP,
  `update_at` TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  `created_by` INT NULL DEFAULT NULL,
  `deleted` TINYINT(1) NULL DEFAULT '0',
  `password_hash` VARCHAR(225) NOT NULL,
  PRIMARY KEY (`id_usuario`),
  UNIQUE INDEX `id_usuario` (`id_usuario` ASC) VISIBLE,
  UNIQUE INDEX `nombre_usuario` (`nombre_usuario` ASC) VISIBLE,
  UNIQUE INDEX `correo_usuario` (`correo_usuario` ASC) VISIBLE,
  UNIQUE INDEX `telefono_usuario` (`telefono_usuario` ASC) VISIBLE)
ENGINE = InnoDB
AUTO_INCREMENT = 6
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `bibliossad`.`prestamos`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `bibliossad`.`prestamos` (
  `id_prestamo` INT NOT NULL AUTO_INCREMENT,
  `fecha_prestamo` DATETIME NOT NULL,
  `fecha_devolucion` DATETIME NOT NULL,
  `fecha_limite` DATETIME NOT NULL,
  `created_at` TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP,
  `update_at` TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  `created_by` INT NULL DEFAULT NULL,
  `deleted` TINYINT(1) NULL DEFAULT '0',
  `estado_prestamo_id` INT NULL DEFAULT NULL,
  `usuario_id` INT NULL DEFAULT NULL,
  `libro_id` INT NULL DEFAULT NULL,
  PRIMARY KEY (`id_prestamo`),
  UNIQUE INDEX `id_prestamo` (`id_prestamo` ASC) VISIBLE,
  INDEX `estado_prestamo_id` (`estado_prestamo_id` ASC) VISIBLE,
  INDEX `usuario_id` (`usuario_id` ASC) VISIBLE,
  INDEX `libro_id` (`libro_id` ASC) VISIBLE,
  CONSTRAINT `prestamos_ibfk_1`
    FOREIGN KEY (`estado_prestamo_id`)
    REFERENCES `bibliossad`.`estados_prestamos` (`id_estado_prestamo`),
  CONSTRAINT `prestamos_ibfk_2`
    FOREIGN KEY (`usuario_id`)
    REFERENCES `bibliossad`.`usuarios` (`id_usuario`),
  CONSTRAINT `prestamos_ibfk_3`
    FOREIGN KEY (`libro_id`)
    REFERENCES `bibliossad`.`libros` (`id_libro`))
ENGINE = InnoDB
AUTO_INCREMENT = 6
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;

USE `bibliosSad` ;

-- -----------------------------------------------------
-- Table `bibliosSad`.`usuarios`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `bibliosSad`.`usuarios` (
  `id_usuario` INT NOT NULL AUTO_INCREMENT,
  `nombre_usuario` VARCHAR(50) NOT NULL,
  `correo_usuario` VARCHAR(150) NOT NULL,
  `telefono_usuario` VARCHAR(10) NOT NULL,
  `created_at` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `update_at` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  `created_by` INT NULL DEFAULT NULL,
  `deleted` TINYINT(1) NULL DEFAULT 0,
  UNIQUE INDEX (`id_usuario` ASC) VISIBLE,
  PRIMARY KEY (`id_usuario`),
  UNIQUE INDEX (`nombre_usuario` ASC) VISIBLE,
  UNIQUE INDEX (`correo_usuario` ASC) VISIBLE,
  UNIQUE INDEX (`telefono_usuario` ASC) VISIBLE);


-- -----------------------------------------------------
-- Table `bibliosSad`.`nacionalidades`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `bibliosSad`.`nacionalidades` (
  `id_nacionalidad` INT NOT NULL AUTO_INCREMENT,
  `nombre_nacionalidad` VARCHAR(50) NOT NULL,
  `created_at` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `update_at` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  `created_by` INT NULL DEFAULT NULL,
  `deleted` TINYINT(1) NULL DEFAULT 0,
  UNIQUE INDEX (`id_nacionalidad` ASC) VISIBLE,
  PRIMARY KEY (`id_nacionalidad`),
  UNIQUE INDEX (`nombre_nacionalidad` ASC) VISIBLE);


-- -----------------------------------------------------
-- Table `bibliosSad`.`autores`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `bibliosSad`.`autores` (
  `id_autor` INT NOT NULL AUTO_INCREMENT,
  `nombre_autor` VARCHAR(50) NOT NULL,
  `apellido_autor` VARCHAR(50) NOT NULL,
  `fecha_nacimiento` DATETIME NOT NULL,
  `fecha_fallecimiento` DATETIME NOT NULL,
  `nacionalidad_id` INT NULL DEFAULT NULL,
  `created_at` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `update_at` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  `created_by` INT NULL DEFAULT NULL,
  `deleted` TINYINT(1) NULL DEFAULT 0,
  UNIQUE INDEX (`id_autor` ASC) VISIBLE,
  PRIMARY KEY (`id_autor`),
  INDEX (`nacionalidad_id` ASC) VISIBLE,
  CONSTRAINT ``
    FOREIGN KEY (`nacionalidad_id`)
    REFERENCES `bibliosSad`.`nacionalidades` (`id_nacionalidad`));


-- -----------------------------------------------------
-- Table `bibliosSad`.`estados_libros`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `bibliosSad`.`estados_libros` (
  `id_estado_libro` INT NOT NULL AUTO_INCREMENT,
  `nombre_estado_libro` VARCHAR(50) NOT NULL,
  `descripcion_estado_libro` VARCHAR(200) NOT NULL,
  `created_at` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `update_at` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  `created_by` INT NULL DEFAULT NULL,
  `deleted` TINYINT(1) NULL DEFAULT 0,
  UNIQUE INDEX (`id_estado_libro` ASC) VISIBLE,
  PRIMARY KEY (`id_estado_libro`),
  UNIQUE INDEX (`nombre_estado_libro` ASC) VISIBLE);


-- -----------------------------------------------------
-- Table `bibliosSad`.`generos_libros`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `bibliosSad`.`generos_libros` (
  `id_genero_libro` INT NOT NULL AUTO_INCREMENT,
  `nombre_genero_libro` VARCHAR(50) NOT NULL,
  `descripcion_genero_libro` VARCHAR(200) NOT NULL,
  `created_at` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `update_at` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  `created_by` INT NULL DEFAULT NULL,
  `deleted` TINYINT(1) NULL DEFAULT 0,
  UNIQUE INDEX (`id_genero_libro` ASC) VISIBLE,
  PRIMARY KEY (`id_genero_libro`),
  UNIQUE INDEX (`nombre_genero_libro` ASC) VISIBLE);


-- -----------------------------------------------------
-- Table `bibliosSad`.`estados_prestamos`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `bibliosSad`.`estados_prestamos` (
  `id_estado_prestamo` INT NOT NULL AUTO_INCREMENT,
  `nombre_estado_prestamo` VARCHAR(50) NOT NULL,
  `descripcion_estado_prestamo` VARCHAR(200) NOT NULL,
  `created_at` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `update_at` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  `created_by` INT NULL DEFAULT NULL,
  `deleted` TINYINT(1) NULL DEFAULT 0,
  UNIQUE INDEX (`id_estado_prestamo` ASC) VISIBLE,
  PRIMARY KEY (`id_estado_prestamo`),
  UNIQUE INDEX (`nombre_estado_prestamo` ASC) VISIBLE);


-- -----------------------------------------------------
-- Table `bibliosSad`.`libros`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `bibliosSad`.`libros` (
  `id_libro` INT NOT NULL AUTO_INCREMENT,
  `titulo` VARCHAR(50) NOT NULL,
  `resumen_libro` VARCHAR(200) NOT NULL,
  `created_at` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `update_at` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  `created_by` INT NULL DEFAULT NULL,
  `deleted` TINYINT(1) NULL DEFAULT 0,
  `autor_id` INT NOT NULL,
  `genero_id` INT NOT NULL,
  `estado_libro_id` INT NOT NULL,
  UNIQUE INDEX (`id_libro` ASC) VISIBLE,
  PRIMARY KEY (`id_libro`),
  INDEX (`autor_id` ASC) VISIBLE,
  INDEX (`genero_id` ASC) VISIBLE,
  INDEX (`estado_libro_id` ASC) VISIBLE,
  CONSTRAINT ``
    FOREIGN KEY (`autor_id`)
    REFERENCES `bibliosSad`.`autores` (`id_autor`),
  CONSTRAINT ``
    FOREIGN KEY (`genero_id`)
    REFERENCES `bibliosSad`.`generos_libros` (`id_genero_libro`),
  CONSTRAINT ``
    FOREIGN KEY (`estado_libro_id`)
    REFERENCES `bibliosSad`.`estados_libros` (`id_estado_libro`));


-- -----------------------------------------------------
-- Table `bibliosSad`.`prestamos`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `bibliosSad`.`prestamos` (
  `id_prestamo` INT NOT NULL AUTO_INCREMENT,
  `fecha_prestamo` DATETIME NOT NULL,
  `fecha_devolucion` DATETIME NOT NULL,
  `fecha_limite` DATETIME NOT NULL,
  `created_at` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `update_at` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  `created_by` INT NULL DEFAULT NULL,
  `deleted` TINYINT(1) NULL DEFAULT 0,
  `estado_prestamo_id` INT NULL DEFAULT NULL,
  `usuario_id` INT NULL DEFAULT NULL,
  `libro_id` INT NULL DEFAULT NULL,
  UNIQUE INDEX (`id_prestamo` ASC) VISIBLE,
    PRIMARY KEY (`id_prestamo`),
    INDEX (`estado_prestamo_id` ASC) VISIBLE,
    INDEX (`usuario_id` ASC) VISIBLE,
    INDEX (`libro_id` ASC) VISIBLE,
    CONSTRAINT ``
    FOREIGN KEY (`estado_prestamo_id`)
    REFERENCES `bibliosSad`.`estados_prestamos` (`id_estado_prestamo`),
    CONSTRAINT ``
    FOREIGN KEY (`usuario_id`)
    REFERENCES `bibliosSad`.`usuarios` (`id_usuario`),
    CONSTRAINT ``
    FOREIGN KEY (`libro_id`)
    REFERENCES `bibliosSad`.`libros` (`id_libro`));


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
