-- MySQL Script generated by MySQL Workbench
-- Tue May 19 12:15:31 2026
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';
-- -----------------------------------------------------
-- Schema sistema_mensajes
-- -----------------------------------------------------
 CREATE DATABASE IF NOT EXISTS `sistema_mensajes` DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci;
 USE `sistema_mensajes`;

-- -----------------------------------------------------
-- Table `sistema_mensajes`.`estado_comentarios`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `sistema_mensajes`.`estado_comentarios` (
    `id_estado` INT NOT NULL AUTO_INCREMENT,
    `nombre_estado` VARCHAR(50) NOT NULL,
    `descripcion_estado` VARCHAR(300) NOT NULL,
    PRIMARY KEY (`id_estado`),
    UNIQUE INDEX `id_estado` (`id_estado` ASC) VISIBLE
) ENGINE = InnoDB DEFAULT CHARACTER SET = utf8mb4 COLLATE = utf8mb4_0900_ai_ci;

-- -----------------------------------------------------
-- Table `sistema_mensajes`.`estado_mensajes`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `sistema_mensajes`.`estado_mensajes` (
    `id_estado` INT NOT NULL AUTO_INCREMENT,
    `nombre_estado` VARCHAR(50) NOT NULL,
    `descripcion_estado` VARCHAR(300) NOT NULL,
    PRIMARY KEY (`id_estado`),
    UNIQUE INDEX `id_estado` (`id_estado` ASC) VISIBLE
) ENGINE = InnoDB DEFAULT CHARACTER SET = utf8mb4 COLLATE = utf8mb4_0900_ai_ci;

-- -----------------------------------------------------
-- Table `sistema_mensajes`.`roles_usuarios`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `sistema_mensajes`.`roles_usuarios` (
    `id_rol_usuario` INT NOT NULL AUTO_INCREMENT,
    `nombre_rol` VARCHAR(50) NOT NULL,
    `descripcion_rol` VARCHAR(200) NOT NULL,
    `created_at` TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    `update_at` TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    `created_by` INT NULL,
    `deleted` TINYINT(1) DEFAULT 0,
    PRIMARY KEY (`id_rol_usuario`),
    UNIQUE INDEX `id_rol_usuario` (`id_rol_usuario` ASC) VISIBLE
) ENGINE = InnoDB DEFAULT CHARACTER SET = utf8mb4 COLLATE = utf8mb4_0900_ai_ci;

-- DIEGO MUERE DEBEMOS SACARLO DEL SISTEMA. BORRADO FÍSICO DELETE FROM usuario_id
-- CON DELETE EL DATO DEJA DE EXISTIR NO SE PUEDE RECUPERAR
-- EN CAMBIO CON BORRADO LÓGICO (campo deleted activo deleted 1))
-- PODEMOS OCULTAR EL USUARIO PARA QUE EL CLIENTE NO LO VEA
-- PERO NO SALE DEL SISTEMA.
-- -----------------------------------------------------
-- Table `sistema_mensajes`.`usuarios`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `sistema_mensajes`.`usuarios` (
    `id_usuario` INT NOT NULL AUTO_INCREMENT,
    `nombre_usuario` VARCHAR(100) NOT NULL,
    `email_usuario` VARCHAR(100) NOT NULL,
    `password_hash` VARCHAR(255) NOT NULL,
    `created_at` TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    `update_at` TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    `deleted` TINYINT(1) DEFAULT 0,
    `rol_usuario_id` INT NOT NULL,
    `created_by` INT NULL DEFAULT NULL,
    PRIMARY KEY (`id_usuario`),
    UNIQUE INDEX `id_usuario` (`id_usuario` ASC) VISIBLE,
    UNIQUE INDEX `nombre_usuario` (`nombre_usuario` ASC) VISIBLE,
    UNIQUE INDEX `email_usuario` (`email_usuario` ASC) VISIBLE,
    INDEX `rol_usuario_id` (`rol_usuario_id` ASC) VISIBLE,
    INDEX `created_by` (`created_by` ASC) VISIBLE,
    CONSTRAINT `usuarios_ibfk_1` FOREIGN KEY (`rol_usuario_id`) REFERENCES `sistema_mensajes`.`roles_usuarios` (`id_rol_usuario`),
    CONSTRAINT `usuarios_ibfk_2` FOREIGN KEY (`created_by`) REFERENCES `sistema_mensajes`.`usuarios` (`id_usuario`)
) ENGINE = InnoDB DEFAULT CHARACTER SET = utf8mb4 COLLATE = utf8mb4_0900_ai_ci;

-- -----------------------------------------------------
-- Table `sistema_mensajes`.`mensajes`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `sistema_mensajes`.`mensajes` (
    `id_mensaje` INT NOT NULL AUTO_INCREMENT,
    `texto_mensaje` TEXT NOT NULL,
    `created_at` TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    `update_at` TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    `created_by` INT NULL,
    `deleted` TINYINT(1) DEFAULT 0,
    `estado_mensaje_id` INT NOT NULL,
    `remitente_mensaje_id` INT NOT NULL,
    `destinatario_mensaje_id` INT NOT NULL,
    PRIMARY KEY (`id_mensaje`),
    UNIQUE INDEX `id_mensaje` (`id_mensaje` ASC) VISIBLE,
    INDEX `estado_mensaje_id` (`estado_mensaje_id` ASC) VISIBLE,
    INDEX `remitente_mensaje_id` (`remitente_mensaje_id` ASC) VISIBLE,
    INDEX `destinatario_mensaje_id` (`destinatario_mensaje_id` ASC) VISIBLE,
    CONSTRAINT `mensajes_ibfk_1` FOREIGN KEY (`estado_mensaje_id`) REFERENCES `sistema_mensajes`.`estado_mensajes` (`id_estado`),
    CONSTRAINT `mensajes_ibfk_2` FOREIGN KEY (`remitente_mensaje_id`) REFERENCES `sistema_mensajes`.`usuarios` (`id_usuario`),
    CONSTRAINT `mensajes_ibfk_3` FOREIGN KEY (`destinatario_mensaje_id`) REFERENCES `sistema_mensajes`.`usuarios` (`id_usuario`)
) ENGINE = InnoDB DEFAULT CHARACTER SET = utf8mb4 COLLATE = utf8mb4_0900_ai_ci;

-- -----------------------------------------------------
-- Table `sistema_mensajes`.`comentarios`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `sistema_mensajes`.`comentarios` (
    `id_comentario` INT NOT NULL AUTO_INCREMENT,
    `texto_comentario` VARCHAR(300) NOT NULL,
    `created_at` TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    `update_at` TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    `created_by` INT NULL,
    `deleted` TINYINT(1) DEFAULT 0,
    `estado_comentario_id` INT NOT NULL,
    `mensaje_id` INT NOT NULL,
    `usuario_id` INT NOT NULL,
    PRIMARY KEY (`id_comentario`),
    UNIQUE INDEX `id_comentario` (`id_comentario` ASC) VISIBLE,
    INDEX `estado_comentario_id` (`estado_comentario_id` ASC) VISIBLE,
    INDEX `mensaje_id` (`mensaje_id` ASC) VISIBLE,
    INDEX `usuario_id` (`usuario_id` ASC) VISIBLE,
    CONSTRAINT `comentarios_ibfk_1` FOREIGN KEY (`estado_comentario_id`) REFERENCES `sistema_mensajes`.`estado_comentarios` (`id_estado`),
    CONSTRAINT `comentarios_ibfk_2` FOREIGN KEY (`mensaje_id`) REFERENCES `sistema_mensajes`.`mensajes` (`id_mensaje`),
    CONSTRAINT `comentarios_ibfk_3` FOREIGN KEY (`usuario_id`) REFERENCES `sistema_mensajes`.`usuarios` (`id_usuario`)
) ENGINE = InnoDB DEFAULT CHARACTER SET = utf8mb4 COLLATE = utf8mb4_0900_ai_ci;

SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;